server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # 1. Routage de l'application Angular (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Reverse Proxy vers l'API
    location /api/ {
        # ATTENTION AU SLASH FINAL : il transforme "/api/endpoint" en "/endpoint" pour ton API.
        proxy_pass http://dragons-api:8080/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'keep-alive';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
